/**
 * Transcript formatting utilities.
 */

export function formatTimestamp(seconds: number): string {
  if (!isFinite(seconds) || isNaN(seconds)) return '--:--';
  const total = Math.floor(seconds);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;

  if (h > 0) {
    return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  }
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

export interface TranscriptRow {
  id: string;
  segment_index: number;
  timestamp_seconds: number;
  original_text: string;
  english_text: string | null;
  speaker: string | null;
}

/**
 * Convert transcript rows to a plain-text format for download.
 */
export function transcriptToTxt(
  rows: TranscriptRow[],
  meetingTitle: string,
  createdAt: string
): string {
  const lines: string[] = [
    `Basha Transcript`,
    `Meeting: ${meetingTitle}`,
    `Date: ${new Date(createdAt).toLocaleString()}`,
    `Generated by Basha`,
    '',
    '='.repeat(60),
    '',
  ];

  for (const row of rows) {
    const ts = formatTimestamp(row.timestamp_seconds ?? 0);
    const speakerLabel = row.speaker
      ? row.speaker.replace(/SPEAKER_0*(\d+)/, (_, n) => `Speaker ${parseInt(n, 10) + 1}`)
      : null;
    lines.push(speakerLabel ? `[${ts}] ${speakerLabel}` : `[${ts}]`);
    lines.push(`Original: ${row.original_text}`);
    if (row.english_text) {
      lines.push(`English:  ${row.english_text}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
